trigger:
  branches:
    include:
      - master

pool:
  name: Self-Hosted
  demands:
    - agent.os -equals Debian

steps:
  - script: |
      # Install the necessary dependencies
      apt-get update
      apt-get install -y python3 python3-pip
      
      # Install the required Python packages
      pip3 install flask
      
      # Build the Python script
      python3 -m py_compile worldcup2026countdown.py
    displayName: 'Build Python script'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/'
      TargetFolder: '/home/user/app'
      OverWrite: true
      CleanTargetFolder: true

  - script: |
      # Start the Flask app
      cd /home/user/app
      nohup python3 worldcup2026countdown.py &
      disown
    displayName: 'Start Flask app'
