# Configure the pipeline
trigger: none

# Specify the agent pool
pool:
  name: debian

# Define the pipeline steps
jobs:
  - job: test
    displayName: Test the World Cup countdown script
    steps:
      - script: |
          # Set up the Python virtual environment
          python -m venv env
          source env/bin/activate

          # Run the test script
          python test.py
        name: Test the script
    agent:
      name: gammez
