# Define a variable to be used on later steps
#variables:
#  nextvmid: 0
      
# Configure the pipeline
trigger: none

# Specify the agent pool
pool:
  name: debian

# Define the pipeline steps
jobs:    
  - job: find_latest_vmid
    displayName: Find latest VMid in Proxmox
    steps:
      # Run the script
      - bash: |
          # Get the last available VMid
          list=$(qm list; pct list)
          lastid=$(echo "$list" | sort -k1,1n | tail -n1 | awk '{print $1}')
          nextid=$(($lastid+1))
          #echo "##vso[task.setvariable isOutput=true;variable=nextvmid;]$nextid" # Somehow is not saving the variable
          echo $nextid > /tmp/nextid.out          

  - job: create_lxc
    displayName: Create LXC in Proxmox
    dependsOn: find_latest_vmid
    steps:
      # Run the script
      - bash: |
          nextid=$(cat /tmp/nextid.out)
          # Create the container with the next available ID
          pct create $nextid /var/lib/vz/template/cache/debian-10.0-standard_10.0-1_amd64.tar.gz --hostname=mycontainer --storage=large --net0 name=eth0,bridge=vmbr0,ip=dhcp --nameserver=8.8.8.8

  - job: run_lxc
    displayName: Run LXC in Proxmox
    dependsOn: create_lxc
    steps:
      # Run the script
      - bash: |
          nextid=$(cat /tmp/nextid.out)
          pct start $nextid
          
  - job: prepare_lxc
    displayName: Install dependencies in the LXC
    dependsOn: run_lxc
    steps:
      # Run the script
      - bash: |
          nextid=$(cat /tmp/nextid.out)
          # Install dependencies
          pct exec $nextid -- apt -y update
          pct exec $nextid -- apt install -y python3-pip git
          pct exec $nextid -- pip3 install flask datetime
          
          # Clone Git repository
          pct exec $nextid -- git clone https://github.com/zingaya/worldcup2026.git
          
          # Make sure I have a path for executing Python
          pct exec $nextid -- export PATH=$PATH:/usr/local/bin
        
  - job: run_worldcup2026countdown
    displayName: Run the WorldCup 2026 Countdown app
    dependsOn: prepare_lxc
    steps:
      # Run the script
      - bash: |
          nextid=$(cat /tmp/nextid.out)
          # Execute Python script
          pct exec $nextid -- nohup python3 worldcup2026/worldcup2026countdown.py &
        
#      # Send the pipeline status to Zabbix
#      - script: |
#          # Get the pipeline status
#          status = "$(Pipeline.Status)"
#
#          # Send the pipeline status to Zabbix using zabbix_sender
#          subprocess.run(["zabbix_sender", "--zabbix-server", "http://parameter", "--host", "World cup timer", "--key", "get.pipeline.trapper", "--value", status])
#        name: Send_the_pipeline_status_to_Zabbix
